version: "3.9"
services:
  node:
    image: node:lts
    ports:
      - "5173:5173"
    command: |
      bash -c "cd front-vue &&
        npm install &&
        npm run lint -- --no-fix --max-warnings 0 &&
        npm audit &&
        npm run build -- --outDir ../target/random-stuff-website-1.0.0/WEB-INF/classes/resources &&
        chown -R `cat user.txt` ../target"
    working_dir: /app
    volumes:
      - ..:/app
    tmpfs:
      - /app/front-vue/node_modules:exec
