<%@ page import="java.util.List, java.text.DecimalFormat, static org.apache.commons.text.StringEscapeUtils.escapeHtml4, static com.max480.randomstuff.gae.UpdateCheckerStatusService.LatestUpdatesEntry"%>

<h1 class="mt-4">Everest Update Checker status page</h1>

<p class="last-refresh">
    Page last refreshed on
    <span class="timestamp-long" data-timestamp="<%= java.time.ZonedDateTime.now().toEpochSecond() %>">
        <%= java.time.ZonedDateTime.now().format(java.time.format.DateTimeFormatter.ofLocalizedDateTime(java.time.format.FormatStyle.LONG)) %>
    </span>
</p>

<% if ((boolean) request.getAttribute("up")) { %>
    <div class="alert alert-success"><b>The update checker is up and running!</b></div>
<% } else { %>
    <div class="alert alert-danger">
        <b>The update checker is currently having issues.</b>
        The mod database might not be up-to-date.
    </div>
<% } %>

<% if (request.getAttribute("lastIncrementalCheckAt") != null) { %>
    <p>
        The database does <i>fast updates</i> <b>every 2 minutes</b>. It only goes through mods that were modified since the last update.
        <br>
        The last <i>fast update</i> happened on
        <b><span class="timestamp-long" data-timestamp="<%= request.getAttribute("lastIncrementalCheckTimestamp") %>">
            <%= request.getAttribute("lastIncrementalCheckAt") %>
        </span>
        (<%= request.getAttribute("lastIncrementalCheckTimeAgo") %>)</b>, and took

        <% if (((double) request.getAttribute("lastIncrementalCheckDuration")) >= 60) { %>
            <%= new DecimalFormat("0.0").format((double) request.getAttribute("lastIncrementalCheckDuration") / 60.0) %> minutes.
        <% } else { %>
            <%= new DecimalFormat("0.0").format((double) request.getAttribute("lastIncrementalCheckDuration")) %> seconds.
        <% } %>
    </p>
<% } %>

<% if (request.getAttribute("lastFullCheckAt") != null) { %>
    <p>
        The database <i>fully updates</i> <b>every hour</b>, when the minute hits 0. It goes through all Celeste mods,
        allowing to detect mod deletions.
        <br>
        The last <i>full update</i> happened on
        <b><span class="timestamp-long" data-timestamp="<%= request.getAttribute("lastFullCheckTimestamp") %>">
            <%= request.getAttribute("lastFullCheckAt") %>
        </span>
        (<%= request.getAttribute("lastFullCheckTimeAgo") %>)</b>, and took

        <% if (((double) request.getAttribute("lastFullCheckDuration")) >= 60) { %>
            <%= new DecimalFormat("0.0").format((double) request.getAttribute("lastFullCheckDuration") / 60.0) %> minutes.
        <% } else { %>
            <%= new DecimalFormat("0.0").format((double) request.getAttribute("lastFullCheckDuration")) %> seconds.
        <% } %>
    </p>
<% } %>

<p>
    This status page is also available <a href="/celeste/update-checker-status.json" target="_blank">in JSON format</a>.
</p>

<p>
    <b><%= request.getAttribute("modCount") %></b> mods are currently registered.
</p>

<div class="alert alert-info">
    <p>
        You can learn more about the files generated by the Everest Update Checker by checking its README
        <a href="https://github.com/maddie480/EverestUpdateCheckerServer/blob/master/README.md" target="_blank">on GitHub</a>.
    </p>
    <p>
        APIs that provide mod search and sorted / filtered lists are also available,
        <a href="https://github.com/maddie480/RandomStuffWebsite/blob/main/README.md#gamebanana-search-api" target="_blank">check the docs here</a>.
    </p>
    <p>
        <b>Not inspired?</b> Try <a href="/celeste/random-map" target="_blank">a random Celeste map</a>.
    </p>
</div>

<% if (!((List<LatestUpdatesEntry>) request.getAttribute("latestUpdates")).isEmpty()) { %>
    <h2>Latest updates</h2>

    <table class="table table-striped">
        <% for (LatestUpdatesEntry entry : (List<LatestUpdatesEntry>) request.getAttribute("latestUpdates")) { %>
            <tr>
                <td>
                    <% if (entry.isAddition) { %>
                        &#x2705;
                    <% } else { %>
                        &#x274c;
                    <% } %>
                </td>
                <td>
                    <span class="timestamp-short" data-timestamp="<%= entry.timestamp %>">
                        <%= escapeHtml4(entry.date) %>
                    </span>
                </td>
                <td>
                    <% if (entry.isAddition) { %>
                        <a href="<%= escapeHtml4(entry.url) %>" target="_blank"><b><%= escapeHtml4(entry.name) %></b></a>
                        was updated to version <b><%= escapeHtml4(entry.version) %></b>
                    <% } else { %>
                        <b><%= escapeHtml4(entry.name) %></b> was deleted
                    <% } %>
                </td>
            </tr>
        <% } %>
    </table>
<% } %>

<script src="/js/timestamp-converter.js"></script>
