name: Website health check
on:
  schedule:
    - cron: "0 0-15 * * *"
    - cron: "*/15 16-20 * * *"
    - cron: "0 21-23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Health check
      env:
        HEALTHCHECK_DISCORD_WEBHOOK_URL: ${{ secrets.HEALTHCHECK_DISCORD_WEBHOOK_URL }}
        DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
      run: |
        if curl --fail -o /dev/null https://maddie480.ovh/
        then
          echo "Health check OK!"
        else
          echo "Health check KO, sending alert!"
          curl --fail -o /dev/null -H 'Content-Type: application/json' -d "{\"content\":\":fire: <@$DISCORD_USER_ID> **maddie480.ovh is down!**\"}" $HEALTHCHECK_DISCORD_WEBHOOK_URL
        fi
